version: '3.1'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
       MYSQL_ROOT_PASSWORD: example
    volumes:
      - blog_db:/var/lib/mysql
  blog:
    image: ghost:alpine
    ports:
      - 9999:2368
    environment:
        database__client: mysql
        database__connection__host: db
        database__connection__user: root
        database__connection__password: example
        database__connection__database: ghost
volumes:
    blog_db:
