version: '2.1'
services:
  web:
    image: nginx:alpine
    depends_on:
        db:
            condition: service_healthy
  db:
    image: mysql:latest
    restart: always
    healthcheck:
      test: "/usr/bin/mysql --user=foo --password=foo --execute \"SHOW DATABASES;\""
      interval: 10s
      retries: 5
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: foo
      MYSQL_USER: foo
      MYSQL_PASSWORD: foo