apiVersion: v1
kind: Service
metadata:
  name: wp-full-blog-service
spec:
  ports:
  - port: 31001
    nodePort: 31001
    targetPort: wp-port
    protocol: TCP

  selector:
    app: wp-full
  type: NodePort