apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wp-full-blog
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: wp-full
    spec:
      containers:
      - name: wp
        image: wordpress:4-php7.0
        ports:
        - name: wp-port
          containerPort: 80
        env:
        - name: WORDPRESS_DB_PASSWORD
          value: root
        - name: WORDPRESS_DB_HOST
          value: 127.0.0.1:3306
        - name: WORDPRESS_DB_PORT
          value: 3306
          
      - name: wp-db
        image: mysql:5.7
        ports:
        - name: mysql-port
          containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root